#!/bin/bash

#SBATCH --partition=gpu_h100
#SBATCH --cpus-per-task=8
#SBATCH --gpus=2
#SBATCH --job-name=ReasonIO
#SBATCH --ntasks=1
#SBATCH --time=25:00:00
#SBATCH --output=logs/slurm/slurm_reasonio_%A.out
#SBATCH --error=logs/slurm/slurm_reasonio_%A.err

module purge
module load 2023
module load Anaconda3/2023.07-2

# Set CUDA options to optimize memory usage
export HYDRA_FULL_ERROR=1

# Activate your environment
source activate logic
# Run your code
sh reason_io_grpo_ablation.sh